### ISSUE TITLE
Adding additional environment variables to the frontend service has no effect

### ISSUE THREAD

**Issue by akoncic** [BulletTrainHQ/bullet-train-docker#8]
Hi,

Seems that adding additional [environment variables](https://github.com/Flagsmith/flagsmith-frontend#env-variables) to the `frontend` service in the compose file has has no effect. I've tried adding `FLAGSMITH`, `FLAGSMITH_CLIENT_API` and `PREVENT_SIGNUP`, to name some, and neither of them seem to be working.

My compose file is as follows:
```yaml
version: "3"

services:
  ...

  frontend:
    container_name: flagsmith_frontend
    image: flagsmith/flagsmith-frontend:latest
    depends_on:
      - api
    networks:
      - flagsmith
    ports:
      - "8080:8080"
    environment:
      API_URL: https://flagsmith-api.example.com/api/v1/
      ASSET_URL: https://flagsmith.example.com/
      ENV: prod
      FLAGSMITH: abcdef
      FLAGSMITH_CLIENT_API: https://flagsmith-api.example.com/api/v1/ # Flagsmith still connects to https://api.flagsmith.com/api/v1/
      PREVENT_SIGNUP: 1 # Signing up is still possible; tried setting the variable to "true" as well, still with no effect
    volumes:
      - frontend-data:/srv/bt
    restart: always

networks:
  flagsmith:

volumes:
  frontend-data: {}
```

Best regards,
Antun

**Comment by dabeeeenster** [comment]
Hi

I'm not able to reproduce this I'm afraid. Are you running the latest version of the tagged container images? 

With:

```
  frontend:
    image: flagsmith/flagsmith-frontend:latest
    environment:
      # You might need to change the 2 host names below depending on your docker dns setup
      #API_URL: http://localhost:8000/api/v1/ 
      #ASSET_URL: http://localhost:8080/
      API_URL: http://docker:8000/api/v1/ 
      ASSET_URL: http://docker:8080/
      FLAGSMITH_CLIENT_API: https://flagsmith-api.example.com/api/v1/ # Flagsmith still connects to https://api.flagsmith.com/api/v1/
    ports:
      - "8080:8080"
    links:
      - api:api
    container_name: flagsmith_frontend
```

I get this in the browser console

```
breadcrumbs.ts:447 GET https://flagsmith-api.example.com/api/v1/flags/ net::ERR_NAME_NOT_RESOLVED
(anonymous) @ breadcrumbs.ts:447
(anonymous) @ index.js:1
t.default @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
value @ index.js:1
(anonymous) @ config-store.js:44
(anonymous) @ config-store.js:27
n @ bootstrap:19
(anonymous) @ ConfigProvider.js:3
n @ bootstrap:19
(anonymous) @ Permission.js:4
(anonymous) @ Permission.js:6
n @ bootstrap:19
(anonymous) @ project-components.js:16
(anonymous) @ project-components.js:94
n @ bootstrap:19
(anonymous) @ main.js:4
(anonymous) @ main.js:61
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ bootstrap:83
breadcrumbs.ts:155 [Delighted] Survey not shown because person is not eligible until Sat Aug 21 2021 01:59:40 GMT+0100 (British Summer Time).
breadcrumbs.ts:447 GET https://flagsmith-api.example.com/api/v1/identities/?identifier=ben.rometsch%40gmail.com net::ERR_NAME_NOT_RESOLVED
(anonymous) @ breadcrumbs.ts:447
(anonymous) @ index.js:1
t.default @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
value @ index.js:1
alias @ api.js:142
setUser @ account-store.js:261
(anonymous) @ account-store.js:191
Promise.then (async)
getOrganisations @ account-store.js:190
onLogin @ account-store.js:116
(anonymous) @ account-store.js:79
(anonymous) @ index.js:35
i @ index.js:31
e.getItem @ index.js:102
setToken @ account-store.js:74
(anonymous) @ account-store.js:352
(anonymous) @ main.js:58
(anonymous) @ main.js:107
dispatch @ main.js:103
handleViewAction @ dispatcher.js:16
setToken @ _app-actions.js:25
(anonymous) @ main.js:63
(anonymous) @ main.js:61
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ bootstrap:83
breadcrumbs.ts:447 POST https://flagsmith-api.example.com/api/v1/traits/ net::ERR_NAME_NOT_RESOLVED
(anonymous) @ breadcrumbs.ts:447
(anonymous) @ index.js:1
t.default @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
alias @ api.js:143
setUser @ account-store.js:261
(anonymous) @ account-store.js:191
Promise.then (async)
getOrganisations @ account-store.js:190
onLogin @ account-store.js:116
(anonymous) @ account-store.js:79
(anonymous) @ index.js:35
i @ index.js:31
e.getItem @ index.js:102
setToken @ account-store.js:74
(anonymous) @ account-store.js:352
(anonymous) @ main.js:58
(anonymous) @ main.js:107
dispatch @ main.js:103
handleViewAction @ dispatcher.js:16
setToken @ _app-actions.js:25
(anonymous) @ main.js:63
(anonymous) @ main.js:61
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ bootstrap:83
breadcrumbs.ts:447 GET https://flagsmith-api.example.com/api/v1/identities/?identifier=ben.rometsch%40gmail.com net::ERR_NAME_NOT_RESOLVED
(anonymous) @ breadcrumbs.ts:447
(anonymous) @ index.js:1
t.default @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
value @ index.js:1
identify @ api.js:171
setUser @ account-store.js:262
(anonymous) @ account-store.js:191
Promise.then (async)
getOrganisations @ account-store.js:190
onLogin @ account-store.js:116
(anonymous) @ account-store.js:79
(anonymous) @ index.js:35
i @ index.js:31
e.getItem @ index.js:102
setToken @ account-store.js:74
(anonymous) @ account-store.js:352
(anonymous) @ main.js:58
(anonymous) @ main.js:107
dispatch @ main.js:103
handleViewAction @ dispatcher.js:16
setToken @ _app-actions.js:25
(anonymous) @ main.js:63
(anonymous) @ main.js:61
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ bootstrap:83
breadcrumbs.ts:447 POST https://flagsmith-api.example.com/api/v1/traits/ net::ERR_NAME_NOT_RESOLVED
(anonymous) @ breadcrumbs.ts:447
(anonymous) @ index.js:1
t.default @ index.js:1
(anonymous) @ index.js:1
(anonymous) @ index.js:1
identify @ api.js:172
setUser @ account-store.js:262
(anonymous) @ account-store.js:191
Promise.then (async)
getOrganisations @ account-store.js:190
onLogin @ account-store.js:116
(anonymous) @ account-store.js:79
(anonymous) @ index.js:35
i @ index.js:31
e.getItem @ index.js:102
setToken @ account-store.js:74
(anonymous) @ account-store.js:352
(anonymous) @ main.js:58
(anonymous) @ main.js:107
dispatch @ main.js:103
handleViewAction @ dispatcher.js:16
setToken @ _app-actions.js:25
(anonymous) @ main.js:63
(anonymous) @ main.js:61
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ bootstrap:83
breadcrumbs.ts:447 POST https://flagsmith-api.example.com/api/v1/traits/ net::ERR_NAME_NOT_RESOLVED
```
