### ISSUE TITLE
I cannot run on ports other that 8000 part of Docker

### ISSUE THREAD

**Issue by ghost** [BulletTrainHQ/bullet-train-docker#9]
Hi,

When I run Flagsmith with the default configuration 8000 everything is fine, but I would like to change that, so if I put say 8030 then the web dashboard is inaccessible and returns an empty response.
I think maybe PORT when put as an environment variable in Docker compose, it is not propagated to the front end part of Flagsmith.

on Firefox:
> The connection was reset

on Chrome:
> ERR_EMPTY_RESPONSE

This is part of my docker compose:

```yml
  flagsmith:
      image: flagsmith/flagsmith:latest
      environment:
          DJANGO_ALLOWED_HOSTS: "*" # Change this in production
          DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@myapp-postgres:5432/flagsmith
          DISABLE_INFLUXDB_FEATURES: "true" # set to 'false' to enable InfluxDB
          ENV: prod # set to "prod" in production.
      ports:
          - "9000:9000"
      depends_on:
          - myapp-postgres
          # - influxdb
      links:
          - myapp-postgres
```
Thanks a lot :)
